server:
    port: 8100
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3307/memorise
        username: root
        password: admin123
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
    privateKey: EOyZ5zHPxtfFZbslS1siLAWzx3EE/b48yLru1eVxNAs=
